name: My Jekyll Website
podcast_url: https://podify.onrender.com/rss
podcast_album_art: /img/art.jpg
podcast_title: Podify
podcast_owner: Podify
podcast_email: podify@gmail.com
podcast_category: General
podcast_explicit: "no"
podcast_author: Jacob Peddicord and Tim Roty
podcast_description: New episode from a different podcast every week.
podcast_summary: New episode from a different podcast every week.
podcast_subtitle: Find new podcasts you'll love.

default:
  -scope:
      path: ""
      type: "posts"